s/DEPRECATEDProviderMetadata StorageProviderMetadata/DEPRECATEDProviderMetadata *StorageProviderMetadata/
s/DEPRECATEDOrchestratorMetadata StorageOrchestratorMetadata/DEPRECATEDOrchestratorMetadata *StorageOrchestratorMetadata/
s/Status StorageClusterStatus/Status *StorageClusterStatus/
s/DynamicConfig StorageDynamicClusterConfig/DynamicConfig *StorageDynamicClusterConfig/
s/TolerationsConfig StorageTolerationsConfig/TolerationsConfig *StorageTolerationsConfig/
